import {createRandomDigits} from "./actions";

export const CHECK = 'CHECK';
export const START_NEW_GAME = 'START_NEW_GAME';
export const GROW_COUNTER_OF_COWS = 'GROW_COUNTER_OF_COWS';
export const REDUCE_COUNTER_OF_COWS = 'REDUCE_COUNTER_OF_COWS';
export const REDUCE_COUNTER_OF_BULLS = 'REDUCE_COUNTER_OF_BULLS';
export const NUMBER_OF_DIGITS = 'NUMBER_OF_DIGITS';
export const SET_ERROR = 'SET_ERROR';
export const CREATE_RANDOM_DIGITS = 'CREATE_RANDOM_DIGITS';
export const DEFINE_NUMBER_OF_DIGITS = 'DEFINE_NUMBER_OF_DIGITS';